### ISSUE TITLE
android/data目录还是空白

### ISSUE THREAD

**Issue by chengzhuangjie** [molihuan/mlhfileselectorlib#1]

**Comment by molihuan** [comment]
还未适配，但是访问权限已经有了，在你的软件上可以通过DocumentFile来操作android/data目录

**Comment by molihuan** [comment]
现在已经适配Android/data目录，欢迎test

**Comment by 1477466721** [comment]
The files and folders inside are all null

**Comment by molihuan** [comment]
> The files and folders inside are all null

Use version 1.0.11 please.There are bugs in version 1.0.10

**Comment by wenwenwenzq** [comment]
安卓12好像是完全访问不了data目录了，安卓11还可以通过那个saf的方法
