### ISSUE TITLE
Add Dpad Support

### ISSUE THREAD

**Issue by usmanali353** [molihuan/mlhfileselectorlib#13]
i want to use this library for android tv but there is no Dpad support can you add D-pad support

**Comment by molihuan** [comment]
> i want to use this library for android tv but there is no Dpad support can you add D-pad support

OK

**Comment by molihuan** [comment]
> i want to use this library for android tv but there is no Dpad support can you add D-pad support

Sorry, because I don't know much about android tv, the focus issue in it is difficult to handle, so you may need to download the source code to handle the adaptation by yourself.
