### ISSUE TITLE
求助关于Leaking

### ISSUE THREAD

**Issue by Pannarrow** [molihuan/mlhfileselectorlib#17]
您好，我在使用BUILD_ACTIVITY时，出现内存泄漏，请问该怎么解决，日志：Leaking: YES (ObjectWatcher was watching this because androidx.fragment.app.FragmentManagerViewModel received ViewModel#onCleared() callback)

**Comment by molihuan** [comment]
> 您好，我在使用BUILD_ACTIVITY时，出现内存泄漏，请问该怎么解决，日志：Leaking: YES (ObjectWatcher was watching this because androidx.fragment.app.FragmentManagerViewModel received ViewModel#onCleared() callback)

关于这个我不是很清楚，我不是做安卓开发的，只是个人需要和兴趣做了这个库，你可以下载源码自己跑，看看源码，逻辑很简单，我门外汉都能了解个七七八八，相信你也可以，等我自己能力提升了和有空闲时间这个库我还是会继续维护的。

**Comment by Pannarrow** [comment]
好吧，最终是把源码抠出来改改用了
