### ISSUE TITLE
isSingle 模式下点击没反应

### ISSUE THREAD

**Issue by cardinlee** [molihuan/mlhfileselectorlib#2]
isSingle 模式下点击没反应
还有可不可以点击一个文件直接返回数据啊，不通过长按

**Comment by molihuan** [comment]
确实有些操作非人性化，已收录，感谢反馈

**Comment by molihuan** [comment]
> isSingle 模式下点击没反应 还有可不可以点击一个文件直接返回数据啊，不通过长按
现在已经修复,可以通过设置fileitem的点击监听来处理你需要的逻辑（返回数据）
issue我关闭了
