### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by vadumpastushok** [molihuan/mlhfileselectorlib#3]
Hi! Needed help in translation. Can't find how to change info above each file and title of storage/emulated/0. These values I want on English.

**Comment by molihuan** [comment]
> Hi! Needed help in translation. Can't find how to change info above each file and title of storage/emulated/0. These values I want on English.

First remove the "io.github.molihuan:pathselector" dependency from your project.

Then download the source code, unzip the package, open "build.gradle" under the pathselector folder, remove the (->id 'com.kezong.fat-aar'<-) and (->apply from: "${getRootDir().absolutePath}/gradles/publish- maven.gradle"<-), modify (->embed(name: 'XXPermissions-13.6', ext: 'aar')<-) to (->implementation fileTree(dir: "libs", includes: ["*.aar", "*.jar"] ) <-) .

 then open your project and pass the pathselector folder into your project by way of a module, then making sure that project build.gradle (no app or pathselector build.gradle) contains the remote repository:
allprojects {
    repositories {
        ...
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

Finally sync Now Get the dependencies

After that you can translate to English by modifying the source code
For example, you search for "内部存储" and change it to "storage"

**Comment by vadumpastushok** [comment]
I thought about changing source code, but hoped that there is another way. Thank for your answer!

**Comment by molihuan** [comment]
> I thought about changing source code, but hoped that there is another way. Thank for your answer!

There is an English translation now
