### ISSUE TITLE
调用.dismiss()方法会出现崩溃现象，请修复

### ISSUE THREAD

**Issue by yw19841107** [molihuan/mlhfileselectorlib#7]
调用.dismiss()方法会出现崩溃现象，请修复

**Comment by molihuan** [comment]
> 调用.dismiss()方法会出现崩溃现象，请修复

已经在1.1.3中修复，请使用:
/**取消dialog弹窗
 * pathSelectFragment.getSelectConfigData().buildController.getDialogFragment().dismiss();
 */
正在上传maven中心仓库，预计40分钟后可以拉取1.1.3版本依赖

**Comment by molihuan** [comment]
> 调用.dismiss()方法会出现崩溃现象，请修复

请注意在Dialog模式中所有的组件都依附于PathSelectDialog所有你必须把PathSelectDialog.dismiss()，可以在配置数据中拿到构建控制者buildController，通过控制者拿到PathSelectDialog。

**Comment by molihuan** [comment]
你还可以通过ConfigDataBuilderImpl.getInstance().getSelectConfigData()静态方法直接拿到配置数据，再通过配置数据中拿到构建控制者buildController，通过控制者拿到PathSelectDialog。

**Comment by molihuan** [comment]
1.1.9已经重写了dismiss()，可以正常调用关闭，内部实现原理还是上面的方法
